### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by davecastlevania** [baylensmith/prj-rev-bwfs-dasmoto#1]
https://github.com/baylensmith/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsCrafts/Resources/CSS/index.css#L17

`  background img: <a href= "https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg";`

This is a big syntax issue

You need to use 

`background-image: url('https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg');`

**Comment by baylensmith** [comment]
Oh yeah, I was way off, wasn't I? That's html language in CSS. Thanks for all your help!
